# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:23
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000'),
        ),
    ]
