# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:38
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_post_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=colorful.fields.RGBColorField(default='#0B70DC'),
        ),
    ]
