# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20160501_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.CharField(default=datetime.datetime(2016, 9, 3, 15, 15, 6, 23856, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
