# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_post_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header',
            new_name='tutorial',
        ),
    ]
